export enum EventType {
  CHAT = 'CHAT',
  REMOVED_FROM_CHAT = 'REMOVED_FROM_CHAT',
  NEW_CHAT_MESSAGE = 'NEW_CHAT_MESSAGE',
  NEW_ISSUE_COMMENT = 'NEW_ISSUE_COMMENT',
  NEW_ISSUE = 'NEW_ISSUE',
  ASSIGNED_TO_ISSUE = 'ASSIGNED_TO_ISSUE'
}
